# TntBlocker Config
# Plugin by alex3025

# Allow players without "tntblocker.place" permission to place tnts.
allow-tnt-placing: true

# Allow players without "tntblocker.grief" permission to destroy blocks with tnts.
allow-tnt-grief: false

# Allow players to take damage from tnts.
allow-tnt-damage: true

# Show in the console a message when a player tries to place a tnt.
placing-warning: true
