name: TntBlocker
main: tntblocker.Main
version: 3.0
author: alex3025
description: A simple minecraft plugin that allows tnt explosion only for users with the permission.
commands:
   tntblocker:
      description: Shows plugin info
      aliases: ['tb', 'tntblock', 'tntb']