name: TntBlocker
main: tntblocker.Main
version: 1.0
author: alex3025
description: A simply minecraft plugin that allows tnt explosion only for OPs.
commands:
   tntblocker:
      description: Shows plugin info
      aliases: ['tb', 'tntblock', 'tntb']